packages:
  - 'phalanx-math'
  - 'phalanx-server'
  - 'phalanx-client'
  - 'phalanx-ecs'
  - 'phalanx-physics'
  - 'phalanx-abilities'
  - 'abilities-playground'
  - 'direct-strike-babylon-example'
  - 'arena-shooter'
  - 'chapaev'
  - 'chapaev/server'
