import { UnitType } from './UnitType';
import type { UnitDefinition } from './UnitDefinition';
import {
  HEAL_AURA_RADIUS,
  HEAL_PULSE_TICKS,
  PLASMA_TANK_ATTACK_COOLDOWN_TICKS,
  PLASMA_TANK_DETECTION_RANGE,
  PLASMA_TANK_MAX_HEALTH,
  PLASMA_TANK_STOP_RANGE,
  ROCKET_DETECTION_RANGE,
  ROCKET_MAX_HEALTH,
  ROCKET_STOP_RANGE,
  SAU_COOLDOWN_TICKS,
  SAU_DETECTION_RANGE,
  SAU_MAX_HEALTH,
  SAU_STOP_RANGE,
  VOLT_DETECTION_RANGE,
} from '../config/abilityDefinitions';

export const UNIT_DEFINITIONS: Readonly<Record<UnitType, UnitDefinition>> = {
  [UnitType.Sphere]: {
    type: UnitType.Sphere,
    radius: 2,
    mass: 2,
    stopRange: 18,
    maxHealth: 100,
    detectionRange: 25,
    heightOffset: 2,
    gridSize: { width: 1, depth: 1 },
    abilities: ['Ability.AutoAttack'],
    hasAutoAttackTimer: true,
    hasCubeState: false,
    visual: {
      shape: 'sphere',
      size: 2,
      hasSpawnArrow: true,
      hasAuraRing: false,
    },
  },
  [UnitType.Cube]: {
    type: UnitType.Cube,
    radius: 2.5,
    mass: 3,
    stopRange: 24,
    maxHealth: 120,
    detectionRange: 32,
    heightOffset: 2.5,
    gridSize: { width: 2, depth: 2 },
    abilities: [],
    hasAutoAttackTimer: false,
    hasCubeState: true,
    visual: { shape: 'box', size: 5, hasSpawnArrow: false, hasAuraRing: false },
  },
  [UnitType.Support]: {
    type: UnitType.Support,
    radius: 2,
    mass: 3,
    stopRange: 22,
    maxHealth: 70,
    detectionRange: 30,
    heightOffset: 2,
    gridSize: { width: 1, depth: 1 },
    abilities: ['Ability.HealAura'],
    hasAutoAttackTimer: false,
    hasCubeState: false,
    aura: { radius: HEAL_AURA_RADIUS, pulseTicks: HEAL_PULSE_TICKS },
    visual: { shape: 'cone', size: 2, hasSpawnArrow: false, hasAuraRing: true },
  },
  [UnitType.Rocket]: {
    type: UnitType.Rocket,
    radius: 2.5,
    mass: 3,
    stopRange: ROCKET_STOP_RANGE,
    maxHealth: ROCKET_MAX_HEALTH,
    detectionRange: ROCKET_DETECTION_RANGE,
    heightOffset: 3,
    gridSize: { width: 2, depth: 1 },
    abilities: ['Ability.MissileVolley'],
    hasAutoAttackTimer: false,
    hasCubeState: false,
    visual: {
      shape: 'octahedron',
      size: 3,
      hasSpawnArrow: false,
      hasAuraRing: false,
    },
  },
  [UnitType.Volt]: {
    type: UnitType.Volt,
    radius: 1.2,
    mass: 2,
    stopRange: 16,
    maxHealth: 200,
    detectionRange: VOLT_DETECTION_RANGE,
    heightOffset: 2.8,
    gridSize: { width: 1, depth: 1 },
    abilities: ['Ability.Volt.ChainLightning'],
    hasAutoAttackTimer: false,
    hasCubeState: false,
    visual: {
      shape: 'volt',
      size: 2.2,
      hasSpawnArrow: false,
      hasAuraRing: false,
    },
  },
  [UnitType.PlasmaTank]: {
    type: UnitType.PlasmaTank,
    radius: 2,
    mass: 2,
    stopRange: PLASMA_TANK_STOP_RANGE,
    maxHealth: PLASMA_TANK_MAX_HEALTH,
    detectionRange: PLASMA_TANK_DETECTION_RANGE,
    heightOffset: 2.5,
    gridSize: { width: 1, depth: 1 },
    abilities: ['Ability.PlasmaTank.MachineGun'],
    hasAutoAttackTimer: true,
    hasCubeState: false,
    hasTurret: true,
    autoAttack: {
      abilityId: 'Ability.PlasmaTank.MachineGun',
      cooldownTicks: PLASMA_TANK_ATTACK_COOLDOWN_TICKS,
    },
    visual: {
      shape: 'plasmaTank',
      size: 2.8,
      hasSpawnArrow: false,
      hasAuraRing: false,
    },
  },
  [UnitType.Sau]: {
    type: UnitType.Sau,
    radius: 2.2,
    mass: 4,
    stopRange: SAU_STOP_RANGE,
    maxHealth: SAU_MAX_HEALTH,
    detectionRange: SAU_DETECTION_RANGE,
    heightOffset: 2.5,
    gridSize: { width: 1, depth: 2 },
    abilities: ['Ability.SAU.Artillery'],
    hasAutoAttackTimer: true,
    hasCubeState: false,
    autoAttack: {
      abilityId: 'Ability.SAU.Artillery',
      cooldownTicks: SAU_COOLDOWN_TICKS,
    },
    visual: {
      shape: 'sau',
      size: 3.8,
      hasSpawnArrow: false,
      hasAuraRing: false,
    },
  },
} as const;
