import { UnitType } from './UnitType';
import type { UnitDefinition } from './UnitDefinition';
import {
  HEAL_AURA_RADIUS,
  HEAL_PULSE_TICKS,
  ROCKET_DETECTION_RANGE,
  ROCKET_MAX_HEALTH,
  ROCKET_STOP_RANGE,
} from '../config/abilityDefinitions';

export const UNIT_DEFINITIONS: Readonly<Record<UnitType, UnitDefinition>> = {
  [UnitType.Sphere]: {
    type: UnitType.Sphere,
    radius: 2,
    mass: 2,
    stopRange: 18,
    maxHealth: 100,
    detectionRange: 25,
    heightOffset: 2,
    gridSize: { width: 1, depth: 1 },
    abilities: ['Ability.AutoAttack'],
    hasAutoAttackTimer: true,
    hasCubeState: false,
    visual: { shape: 'sphere', size: 2, hasSpawnArrow: true, hasAuraRing: false },
  },
  [UnitType.Cube]: {
    type: UnitType.Cube,
    radius: 2.5,
    mass: 3,
    stopRange: 24,
    maxHealth: 120,
    detectionRange: 32,
    heightOffset: 2.5,
    gridSize: { width: 2, depth: 2 },
    abilities: [],
    hasAutoAttackTimer: false,
    hasCubeState: true,
    visual: { shape: 'box', size: 5, hasSpawnArrow: false, hasAuraRing: false },
  },
  [UnitType.Support]: {
    type: UnitType.Support,
    radius: 2,
    mass: 3,
    stopRange: 22,
    maxHealth: 70,
    detectionRange: 25,
    heightOffset: 2,
    gridSize: { width: 1, depth: 1 },
    abilities: ['Ability.HealAura'],
    hasAutoAttackTimer: false,
    hasCubeState: false,
    aura: { radius: HEAL_AURA_RADIUS, pulseTicks: HEAL_PULSE_TICKS },
    visual: { shape: 'cone', size: 2, hasSpawnArrow: false, hasAuraRing: true },
  },
  [UnitType.Rocket]: {
    type: UnitType.Rocket,
    radius: 2.5,
    mass: 3,
    stopRange: ROCKET_STOP_RANGE,
    maxHealth: ROCKET_MAX_HEALTH,
    detectionRange: ROCKET_DETECTION_RANGE,
    heightOffset: 3,
    gridSize: { width: 2, depth: 1 },
    abilities: ['Ability.MissileVolley'],
    hasAutoAttackTimer: false,
    hasCubeState: false,
    visual: { shape: 'octahedron', size: 3, hasSpawnArrow: false, hasAuraRing: false },
  },
} as const;
